version: '3.7'
services:
  runway:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ~/.aws:/aws
    environment:
      - AWS_CONFIG_FILE=/aws/config
      - AWS_DEFAULT_PROFILE
      - AWS_SHARED_CREDENTIALS_FILE=/aws/credentials
      - AWS_DEFAULT_REGION
      - CI=1
      - DEPLOY_ENVIRONMENT
      - GIT_BRANCH
    command:
      - runway
      - takeoff

  runway-destroy:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ~/.aws:/aws
    environment:
      - AWS_CONFIG_FILE=/aws/config
      - AWS_DEFAULT_PROFILE
      - AWS_SHARED_CREDENTIALS_FILE=/aws/credentials
      - AWS_DEFAULT_REGION
      - CI=1
      - DEPLOY_ENVIRONMENT
      - GIT_BRANCH
    command:
      - runway
      - destroy
